language: elixir
elixir:
  - 1.9
otp_release:
  - 22.1.8
cache:
  directories:
    - _build
    - deps
script:
  - mix do deps.get, compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - MIX_ENV=test
    - AWS_REGION=eu-west-1
    - RECIPIENT_EMAIL=success@simulator.amazonses.com
